server:
    port: 8000

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            default-zone: http://localhost:9720/eureka

spring:
    application:
        name: api-gateway
        # java code에 의해 정할 수 있다
    cloud:
        gateway:
            default-filters:
                - name : GlobalFilter
                  args:
                    baseMessage: this is global filter
                    preFilter: true
                    postFilter: true

            routes:
                - id: user-service
                  uri: lb://USER-SERVICE
                  predicates:
                      - Path=/user-service/**
                  filters:
#                      - AddRequestHeader=userservice-request, request
#                      - AddResponseHeader=userservice-response, response
                      - name: CustomFilter
                      - name: LoggingFilter
                        args:
                          baseMessage: this is logging filter
                          preFilter: true
                          postFilter: true
